/**
 * QwenProxy TUI - Lightweight Terminal Markdown Formatter
 * Formats Markdown bold, italic, code blocks, bullet lists, and headers into ANSI styles
 * with word-wrapping that respects terminal column constraints.
 */

import { theme, stringWidth } from "./theme.ts";
export interface MarkdownOptions {
  dim?: boolean;
}

/**
 * Formats Qwen's internal reasoning into a uniform, subdued, all-italic monologue.
 * Strips distracting markdown formatting and keeps every thought in a homogeneous opaque tone.
 */
export function formatReasoning(content: string, maxWidth: number): string[] {
  const rawLines = content.split("\n");
  const result: string[] = [];
  const dimItalic = (s: string) => `\x1b[3m\x1b[38;2;120;125;145m${s}\x1b[39m\x1b[23m`;

  for (const raw of rawLines) {
    const trimmed = raw.trimEnd();
    if (!trimmed) {
      result.push("");
      continue;
    }
    // Strip markdown asterisks and backticks so thoughts don't have clashing colors
    const cleanText = trimmed
      .replace(/(\*\*|__)(.*?)\1/g, "$2")
      .replace(/`([^`]+)`/g, "$1")
      .replace(/^#+\s*/, "");

    const wrapped = wrapAnsiLine(cleanText, maxWidth);
    for (const w of wrapped) {
      result.push(dimItalic(w));
    }
  }
  return result;
}


/**
 * Renders an elegant OSC 8 interactive card for images generated by Qwen.
 */
export function formatImageCard(alt: string, url: string, maxWidth: number): string[] {
  const cardW = Math.max(30, Math.min(maxWidth, 70));
  const cleanAlt =
    alt && alt !== "Generated image" && alt !== "image"
      ? ` ${alt.trim()} `
      : " Generated Image ";
  const innerW = cardW - 2;
  const linkLabel = `[ 🔗 Click to open the image in your browser ]`;
  const osc8 = `\x1b]8;;${url}\x1b\\${theme.cyan(theme.underline(linkLabel))}\x1b]8;;\x1b\\`;
  const labelVisualW = stringWidth(linkLabel);
  const paddingRight = " ".repeat(Math.max(0, innerW - labelVisualW - 2));

  const titleW = stringWidth(cleanAlt);
  const topHr = "─".repeat(Math.max(2, innerW - titleW - 5));
  const bottomHr = "─".repeat(innerW);

  return [
    `  ${theme.borderActive(`╭─ 🖼️ ${cleanAlt}${topHr}╮`)}`,
    `  ${theme.borderActive("│")}  ${osc8}${paddingRight}${theme.borderActive("│")}`,
    `  ${theme.borderActive(`╰${bottomHr}╯`)}`,
  ];
}
/**
 * Formats inline Markdown elements (bold, italic, code, strikethrough).
 */
export function formatMarkdownInline(text: string, options?: MarkdownOptions): string {
  const dim = options?.dim ?? false;
  let res = text;

  if (dim) {
    const muted = "\x1b[38;2;120;125;145m";
    const reset = "\x1b[39m";
    // Uniform dimmed italic mode
    res = res.replace(/(\*\*|__)(.*?)\1/g, (_m, _d, content) => `\x1b[3m${content}\x1b[23m`);
    res = res.replace(/(?<!\w)(\*|_)(.*?)\1(?!\w)/g, (_m, _d, content) => `\x1b[3m${content}\x1b[23m`);
    res = res.replace(/`([^`]+)`/g, (_m, content) => `\x1b[3m${content}\x1b[23m`);
    res = res.replace(/~~(.*?)~~/g, (_m, content) => `\x1b[9m${content}\x1b[29m`);
    return `\x1b[3m${muted}${res}${reset}\x1b[23m`;
  }

  // Standard vibrant TrueColor mode (for assistant final responses)
  res = res.replace(/(\*\*|__)(.*?)\1/g, (_m, _d, content) => theme.bold(theme.white(content)));
  res = res.replace(/(?<!\w)(\*|_)(.*?)\1(?!\w)/g, (_m, _d, content) =>
    theme.italic(theme.lavender(content)),
  );
  res = res.replace(/`([^`]+)`/g, (_m, content) => theme.cyan(content));
  res = res.replace(/~~(.*?)~~/g, (_m, content) => `\x1b[9m${content}\x1b[29m`);

  return res;
}

/**
 * Word-wraps a single ANSI-styled string into multiple lines without breaking ANSI sequences.
 */
export function wrapAnsiLine(line: string, maxWidth: number): string[] {
  if (maxWidth <= 0) return [line];
  if (stringWidth(line) <= maxWidth) return [line];

  const words = line.split(" ");
  const lines: string[] = [];
  let currentLine = "";

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    if (stringWidth(testLine) <= maxWidth) {
      currentLine = testLine;
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    }
  }

  if (currentLine) lines.push(currentLine);
  return lines.length > 0 ? lines : [""];
}

/**
 * Parses full multi-line Markdown text and returns an array of formatted, word-wrapped lines.
 */
export function formatMarkdown(
  content: string,
  maxWidth: number,
  options?: MarkdownOptions,
): string[] {
  const rawLines = content.split("\n");
  const result: string[] = [];
  let inCodeBlock = false;
  const isDim = options?.dim ?? false;

  for (const rawLine of rawLines) {
    const trimmed = rawLine.trimEnd();

    // Image Markdown: ![alt](url)
    const imgRegex = /!\[(.*?)\]\((https?:\/\/[^\s)]+)\)/g;
    if (imgRegex.test(trimmed)) {
      const parts = trimmed.split(/(!\[.*?\]\(https?:\/\/[^\s)]+\))/g);
      for (const part of parts) {
        const m = part.match(/^!\[(.*?)\]\((https?:\/\/[^\s)]+)\)$/);
        if (m) {
          result.push(...formatImageCard(m[1], m[2], maxWidth));
        } else if (part.trim()) {
          const inlineFormatted = formatMarkdownInline(part.trim(), options);
          result.push(...wrapAnsiLine(inlineFormatted, maxWidth));
        }
      }
      continue;
    }

    // Code blocks: ```lang ... ```
    if (trimmed.startsWith("```")) {
      inCodeBlock = !inCodeBlock;
      const lang = trimmed.slice(3).trim();
      if (inCodeBlock) {
        const border = isDim ? theme.dark : theme.blue;
        result.push(border(`┌─── ${lang || "code"} ───────────────────────────`));
      } else {
        const border = isDim ? theme.dark : theme.blue;
        result.push(border("└───"));
      }
      continue;
    }

    if (inCodeBlock) {
      if (isDim) {
        result.push(theme.dark(`│ `) + theme.muted(trimmed));
      } else {
        result.push(theme.blue(`│ `) + theme.cyan(trimmed));
      }
      continue;
    }

    // Headers
    if (/^#{1,3}\s+/.test(trimmed)) {
      const level = trimmed.match(/^#+/)?.[0].length || 1;
      const cleanHeader = trimmed.replace(/^#+\s*/, "");
      const formattedHeader = formatMarkdownInline(cleanHeader, options);
      if (isDim) {
        result.push(theme.bold(theme.muted(`■ ${cleanHeader}`)));
      } else {
        if (level === 1) {
          result.push(theme.bold(theme.lavender(`■ ${formattedHeader}`)));
        } else if (level === 2) {
          result.push(theme.bold(theme.blue(`● ${formattedHeader}`)));
        } else {
          result.push(theme.bold(theme.cyan(`▸ ${formattedHeader}`)));
        }
      }
      continue;
    }

    // Blockquotes
    if (trimmed.startsWith(">")) {
      const quoteText = trimmed.replace(/^>\s*/, "");
      const formattedQuote = formatMarkdownInline(quoteText, options);
      const wrapped = wrapAnsiLine(formattedQuote, Math.max(10, maxWidth - 4));
      for (const wl of wrapped) {
        result.push(theme.muted("│ ") + theme.italic(wl));
      }
      continue;
    }

    // Bullet lists (- or * or •)
    if (/^(\s*)[-*•]\s+/.test(trimmed)) {
      const match = trimmed.match(/^(\s*)[-*•]\s+(.*)$/);
      if (match) {
        const indent = match[1] || "";
        const itemText = formatMarkdownInline(match[2], options);
        const wrapped = wrapAnsiLine(itemText, Math.max(10, maxWidth - indent.length - 4));
        const bullet = isDim ? theme.dark("•") : theme.cyan("•");
        wrapped.forEach((wl, idx) => {
          if (idx === 0) {
            result.push(`${indent}  ${bullet} ${wl}`);
          } else {
            result.push(`${indent}    ${wl}`);
          }
        });
        continue;
      }
    }

    // Numbered lists (1. 2.)
    if (/^(\s*)\d+\.\s+/.test(trimmed)) {
      const match = trimmed.match(/^(\s*)(\d+\.)\s+(.*)$/);
      if (match) {
        const indent = match[1] || "";
        const num = match[2];
        const itemText = formatMarkdownInline(match[3], options);
        const wrapped = wrapAnsiLine(itemText, Math.max(10, maxWidth - indent.length - num.length - 3));
        const numStyled = isDim ? theme.muted(num) : theme.blue(num);
        wrapped.forEach((wl, idx) => {
          if (idx === 0) {
            result.push(`${indent}  ${numStyled} ${wl}`);
          } else {
            result.push(`${indent}     ${wl}`);
          }
        });
        continue;
      }
    }

    // Empty lines
    if (!trimmed) {
      result.push("");
      continue;
    }

    // Standard paragraph with inline formatting and word-wrap
    const inlineFormatted = formatMarkdownInline(trimmed, options);
    const wrapped = wrapAnsiLine(inlineFormatted, maxWidth);
    result.push(...wrapped);
  }

  return result;
}
