export const isReadinessControllerEnabled = (): boolean => false;
export const getReadinessDiagnostics = () => ({});
export const triggerReadinessCheck = (_?: any) => {};
export const ensurePoolReadiness = (_: any, __: any) => {};
export const registerReadinessGuardDeps = (_: any) => {};
export const recoveredValidationBucket = (_: any) => 0;
export const startReadinessGuardSweep = () => {};
export const stopReadinessGuardSweep = () => {};
export const resetReadinessCountersForTests = () => {};
export const runReadinessValidationForTests = (_: any, __: any) => Promise.resolve({});
